BLOCK-REPAIR: CHEST #you need post a Minecraft name for example CHEST ANVIL ENDER_CHEST....
MONEY: 300
REPAIR-MESSAGE: "&cHas been repair"
BAD-CLICK: "&cUse your RIGHT CLICK"
NO-MONEY: "&cYou dont have money to repair your item"
NO-ITEM: "&cYou dont have item to repair"