name: sRepair
version: ${project.version}
main: me.sakio.repair.repair.Repair
api-version: 1.8
authors: [Sakio]

commands:
  rreload:
    description: reload all config file
  ritem:
    description: give you a repair item
